# Database connection settings (required)
[db]
driver="postgres"
dsn="postgres://postgres:Rewq_1234@185.121.233.53:5432/loadhound_db?sslmode=disable"

# optional parameters; if omitted, driver defaults are used
# use prepared statements (optional; defaults to false)
# [db.sql_config]
# max_open_connections=4
# max_idle_connections=2
# conn_max_idle_time="1m"
# conn_max_lifetime="10m"
# use_prepared_statements=false

# Query template settings (required)
# To parameterize values, use the built-in template functions (see documentation)
[query_template]
name="insert"
template="""
INSERT INTO tasks (title, description, priority)
VALUES ({{ .randStrRange 10 100 }}, {{ .randStrRange 100 255 }}, {{ .randIntRange 1 3 }});
"""

# Workflow configuration
# type required parameters (options: simple, extend)
# iterations or duration must be set (mutually exclusive)
# pacing between iterations (optional; default: 0 — next iteration starts immediately)
[workflow]
type="simple"
iterations=2
#duration="5m"
threads=1  # number of concurrent threads
pacing="1s" # delay per iteration (Go duration format)

[output.report]
to_file=true # save report in file with name loadhound_report_2006-01-02T15:04:05Z07:00.json
to_console=true

[output.log]
to_file= true # write all JSON structured logs in file with name loadhound_2006-01-02T15:04:05Z07:00.log
to_console=true