[db]
driver="postgres"
dsn="postgres://postgres:passwd@localhost:5432/loadhound_db?sslmode=disable"

[db.conn_pool]
max_open_connections=2
max_idle_connections=2
conn_max_idle_time="1m"
conn_max_lifetime="1m"

[workflow]
[[workflow.scenarios]]
name="select_scenario"
duration="15s"
threads=2
pacing="1s"

[workflow.scenarios.statement]
name="select"
query="select * from loadhound_table lt where lt.rand_bool = $1 and lt.rand_int = $2;"
args="randBool, randIntRange 100 1000"

[output.report]
to_file=true
to_console=true

[output.log]
to_file= false
to_console=true
level="debug"